ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),

    path('shop/', include('orders.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views


app_name = "orders"
urlpatterns = [
    path('', views.ProductListView.as_view(), name="list"),
    path('<int:pk>/', views.ProductDetailView.as_view(), name="detail"),
    path('cart/', views.cart_view, name="cart"),
    path('checkout/', views.checkout_view, name="checkout"),

    path('update_cart/', views.update_cart, name="update_cart"),
    path('process_order/', views.process_order, name="process_order"),
]

orders/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

orders/models/order.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=30, null=True)

    def __str__(self):
        return f"{self.customer.username}: {self.transaction_id}"

    @property
    def total(self):
        return sum([item.total for item in self.orderitem_set.all()])

    @property
    def item_count(self):
        return sum([item.quantity for item in self.orderitem_set.all()])

orders/models/order_item.py
from django.db import models

from ..models import Product, Order


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.name} x {self.quantity}"

    @property
    def total(self):
        return float(self.product.discounted_price) * self.quantity

orders/models/product.py
from django.db import models
from django.urls import reverse

from . import Category


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    details = models.TextField(default="")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    image = models.ImageField(default="no-image-available-1.jpg", upload_to="products")
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def discounted_price(self):
        if self.discount:
            return round(float(self.price) * float(100 - self.discount) / 100, 2)
        else:
            return self.price

    def get_absolute_url(self):
        return reverse("orders:detail", kwargs={"pk": self.pk})

orders/models/shipping_address.py
from django.db import models
from django.contrib.auth.models import User

from ..models import Order


class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

orders/views/cart_view.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from ..models import Order


@login_required
def cart_view(request):
    user = request.user
    order, created = Order.objects.get_or_create(customer=user, ordered=False)
    order_items = order.orderitem_set.all()

    context = {
        "order": order,
        "order_items": order_items,
    }

    return render(request, 'orders/cart.html', context)

orders/views/checkout_view.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from ..models import Order


@login_required
def checkout_view(request):
    user = request.user
    order, created = Order.objects.get_or_create(customer=user, ordered=False)
    order_items = order.orderitem_set.all()

    context = {
        "order": order,
        "order_items": order_items,
    }

    return render(request, "orders/checkout.html", context)

orders/views/process_order.py
from django.http import JsonResponse
import datetime
import json

from ..models import Order, ShippingAddress


def process_order(request):
    data = json.loads(request.body)
    transaction_id = datetime.datetime.now().timestamp()
    order, created = Order.objects.get_or_create(customer=request.user, ordered=False)
    order.transaction_id = transaction_id

    if float(data["shippingInfo"]["total"]) == float(order.total):
        order.ordered = True
        ShippingAddress.objects.create(
            customer=request.user,
            order=order,
            address=data["shippingInfo"]["address"],
            city=data["shippingInfo"]["city"],
            state=data["shippingInfo"]["state"],
            zipcode=data["shippingInfo"]["zipcode"],
        )

    order.save()

    return JsonResponse("Payment complete!", safe=False)

orders/views/product_detail_view.py
from django.views.generic import DetailView

from ..models import Product, Order


class ProductDetailView(DetailView):
    template_name = "orders/product_detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["order"] = Order.objects.get(customer=self.request.user, ordered=False)
        else:
            context["order"] = {"item_count": 0}
        return context

orders/views/product_list_view.py
from django.views.generic import ListView
from django.db.models import Q

from ..models import Product, Category, Order
from ..utils import get_category_filters


class ProductListView(ListView):
    template_name = "orders/product_list.html"
    model = Product
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        sort = self.request.GET.get('sort')
        context = super(ProductListView, self).get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["query"] = self.request.GET.get('query')
        context["category_filters"] = get_category_filters(request=self.request)
        context["sort"] = sort if sort else '-discounted_price'
        if self.request.user.is_authenticated:
            context["order"] = Order.objects.get(customer=self.request.user, ordered=False)
        else:
            context["order"] = {"item_count": 0}
        return context

    def get_queryset(self):
        query = self.request.GET.get('query')
        category_filters = get_category_filters(request=self.request)
        sort = self.request.GET.get('sort')
        sort = sort if sort else '-discounted_price'
        queryset = Product.objects.all()

        if query and query != "None":
            queryset = queryset.filter(
                Q(name__icontains=query)
            )

        if category_filters:
            queryset = queryset.filter(category__name__in=category_filters)

        if sort == "discounted_price":
            queryset = sorted(queryset, key=lambda product: product.discounted_price)
        elif sort == "-discounted_price":
            queryset = sorted(queryset, key=lambda product: product.discounted_price, reverse=True)
        else:
            queryset = queryset.order_by(sort)

        return queryset

orders/views/update_cart.py
from django.http import JsonResponse
import json

from ..models import Product, Order, OrderItem


def update_cart(request):
    data = json.loads(request.body)
    product_id = data["productId"]
    action = data["action"]

    user = request.user
    product = Product.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(customer=user, ordered=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "remove":
        order_item.delete()
    else:
        if action == "add":
            order_item.quantity += 1
        elif action == "subtract":
            order_item.quantity -= 1
        order_item.save()

        if order_item.quantity <= 0:
            order_item.delete()

    return JsonResponse("Item was added", safe=False)

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for item in order_items %}
                    <tr>
                        <td class="align-middle">
                            <a href="{% url 'orders:detail' item.product.id %}" class="text-decoration-none">
                                <img src="{{ item.product.image.url }}" alt="" style="width: 50px;">{{ item.product|title }}
                            </a>
                        </td>
                        {% with item.product.discounted_price|floatformat:2 as unit_price %}
                        <td class="align-middle">${{ unit_price|intcomma }}</td>
                        {% endwith %}
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button data-product="{{ item.product.id }}" data-action="subtract" class="btn btn-sm btn-primary btn-minus update-cart" >
                                    <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary text-center" value="{{ item.quantity }}">
                                <div class="input-group-btn">
                                    <button data-product="{{ item.product.id }}" data-action="add" class="btn btn-sm btn-primary btn-plus update-cart">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        {% with item.total|floatformat:2 as total %}
                        <td class="align-middle">${{ total|intcomma }}</td>
                        {% endwith %}

                        <td class="align-middle">
                            <button data-product="{{ item.product.id }}" data-action="remove" class="btn btn-sm btn-primary update-cart">
                                <i class="fa fa-times"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        {% with order.total|floatformat:2 as total %}
                        <h6 class="font-weight-medium">${{ total|intcomma }}</h6>
                        {% endwith %}
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        {% with order.total|floatformat:2 as total %}
                        <h5 class="font-weight-bold">${{ total|intcomma }}</h5>
                        {% endwith %}
                    </div>
                    <a href="{% url 'orders:checkout' %}" class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% include 'scripts.html' %}
{% endblock scripts %}

orders/templates/orders/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container-fluid pt-5">
    <div class="row px-xl-5">

        <div class="col-lg-8">

            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Order Total</h4>
                </div>
                <div class="card-body">
                    <h5 class="font-weight-medium mb-3">Products</h5>

                    {% for item in order_items %}
                    <div class="d-flex justify-content-between">
                        <p>{{ item|title }}</p>
                        <p>${{ item.total|intcomma|floatformat:2 }}</p>
                    </div>
                    {% endfor %}

                    <hr class="mt-0">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        {% with order.total|floatformat:2 as subtotal %}
                        <h6 class="font-weight-medium">${{ subtotal|intcomma }}</h6>
                        {% endwith %}
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        {% with order.total|floatformat:2 as total %}
                        <h5 class="font-weight-bold">${{ total|intcomma }}</h5>
                        {% endwith %}
                    </div>
                </div>
            </div>


        </div>

        <div class="col-lg-4">

            <form id="shipping-address" class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0 mb-4">
                    <h4 class="font-weight-semi-bold mb-4">Shipping Address</h4>
                </div>
                <div class="row mx-1">
                    <div class="col-md-12 form-group">
                        <label>Address</label>
                        <input name="address" class="form-control" type="text" placeholder="Address">
                    </div>
                    <div class="col-md-12 form-group">
                        <label>City</label>
                        <input name="city" class="form-control" type="text" placeholder="City">
                    </div>
                    <div class="col-md-12 form-group">
                        <label>State</label>
                        <input name="state" class="form-control" type="text" placeholder="State">
                    </div>
                    <div class="col-md-12 form-group">
                        <label>ZIP Code</label>
                        <input name="zipcode" class="form-control" type="text" placeholder="ZIP Code">
                    </div>
                </div>

            </form>

            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Payment</h4>
                </div>
                <div class="m-2">
                    <div id="paypal-button-container"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
{% include 'scripts.html' %}

<script src="https://www.paypal.com/sdk/js?client-id=AUBFxtP_M3r6Q3kSGtw4lFSQE1KvT3wGGMcKs9bPSo72fHozyko2olrPd0xGFXm6sVO21l11u78Uxdkm&currency=USD"></script>

<script>
    var total = "{{ order.total }}"

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(orderData) {
                processPayment()
            });
        }
    }).render('#paypal-button-container');
</script>

<script type="text/javascript">
    var shippingAddress = document.getElementById('shipping-address')

    function processPayment() {
        var shippingInfo = {
            'address': shippingAddress.address.value,
            'city': shippingAddress.city.value,
            'state': shippingAddress.state.value,
            'zipcode': shippingAddress.zipcode.value,
            'total': total,
        }
        var url = "/shop/process_order/"
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application.json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({
                'shippingInfo': shippingInfo,
            })
        })
        .then((response) => {
            return response.json()
        })
        .then((data) => {
            console.log("Data:", data);
            alert("Transaction Completed");
            window.location.href = "{% url 'index' %}";
        })
    }


</script>
{% endblock scripts %}

orders/templates/orders/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid py-5">
    <div class="row px-xl-5">
        <div class="col-lg-5 pb-5">
            <div id="product-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner border">

                    <div class="carousel-item active">
                        <img class="w-100 h-100" src="{{ object.image.url }}" alt="Image">
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-7 pb-5">
            <h3 class="font-weight-semi-bold">{{ object.name|title }}</h3>

            {% if object.discount %}
            <h3 class="font-weight-semi-bold mb-4">${{ object.discounted_price }} <span class="text-muted ml-2"><del>${{ object.price }}</del></span></h3>
            {% else %}
            <h3 class="font-weight-semi-bold mb-4">${{ object.price }}</h3>
            {% endif %}

            <p class="mb-4">{{ object.details }}</p>

            <div class="d-flex align-items-center mb-4 pt-2">
                <button data-product="{{ object.id }}" data-action="add" class="btn btn-primary px-3 update-cart">
                    <i class="fa fa-shopping-cart mr-1"></i> Add To Cart
                </button>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

{% include 'products_suggested.html' %}

{% block scripts %}
{% include 'scripts.html' %}
{% endblock scripts %}

orders/templates/orders/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load url_replace %}

{% block content %}

<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        {% include 'orders/sidebar.html' %}

        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">

                {% for product in object_list %}
                <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                    {% include 'product_box.html' %}
                </div>
                {% endfor %}

                {% if is_paginated %}
                <div class="col-12 pb-1">
                    <nav aria-label="Page navigation">
                      <ul class="pagination justify-content-center mb-3">

                        {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?{% url_replace 'page' 1 %}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range %}
                        {% if page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                        <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                            <a href="?{% url_replace 'page' page %}" class="page-link">{{ page }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="?{% url_replace 'page' page_obj.paginator.num_pages %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                        {% endif %}

                      </ul>
                    </nav>
                </div>
                {% endif %}

            </div>
        </div>
        <!-- Shop Product End -->

    </div>
</div>
{% endblock %}

{% block scripts %}
{% include 'scripts.html' %}
{% endblock scripts %}

orders/templates/orders/sidebar.html
{% load static %}

<div class="col-lg-3 col-md-12">
    <form action="{% url 'orders:list' %}">

        <div class="border-bottom mb-4 pb-4">
            <h5 class="font-weight-semi-bold mb-4">Categories</h5>
            {% for category in categories %}
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="checkbox" class="custom-control-input" id="price-{{ category.id }}" name="category" value="{{ category.name }}" {% if category.name in category_filters %}checked{% endif %}>
                <label class="custom-control-label" for="price-{{ category.id }}">{{ category.name }}</label>
                <span class="badge border font-weight-normal">{{ category.product_set.count }}</span>
            </div>
            {% endfor %}
        </div>

        <div class="border-bottom mb-4 pb-4">
            <h5 class="font-weight-semi-bold mb-4">Sort By</h5>

            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="radio" class="custom-control-input" id="price-asc" name="sort" value="discounted_price" {% if sort == 'discounted_price' %}checked{% endif %}>
                <label class="custom-control-label" for="price-asc">Price (Ascending)</label>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="radio" class="custom-control-input" id="price-desc" name="sort" value="-discounted_price" {% if sort == '-discounted_price' %}checked{% endif %}>
                <label class="custom-control-label" for="price-desc">Price (Descending)</label>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="radio" class="custom-control-input" id="arrival-asc" name="sort" value="date_added" {% if sort == 'date_added' %}checked{% endif %}>
                <label class="custom-control-label" for="arrival-asc">Arrival (Ascending)</label>
            </div>
            <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                <input type="radio" class="custom-control-input" id="arrival-desc" name="sort" value="-date_added" {% if sort == '-date_added' %}checked{% endif %}>
                <label class="custom-control-label" for="arrival-desc">Arrival (Descending)</label>
            </div>

        </div>

        <div>
          <input type="hidden" name="query" value="{{ query }}" />
        </div>

        <div>
            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Filter Products</button>
        </div>
    </form>
</div>