accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.AccountsCreateView.as_view(), name='register'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),

    path('shop/', include('orders.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views


app_name = "orders"
urlpatterns = [
    path('', views.ProductListView.as_view(), name="list"),
    path('<int:pk>/', views.ProductDetailView.as_view(), name="detail"),
    path('cart/', views.cart_view, name="cart"),
    path('checkout/', views.checkout_view, name="checkout"),

    path('update_cart/', views.update_cart, name="update_cart"),
    path('process_order/', views.process_order, name="process_order"),
]

orders/models/product.py
from django.db import models
from django.urls import reverse

from . import Category


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    details = models.TextField(default="")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    image = models.ImageField(default="no-image-available-1.jpg", upload_to="products")
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def discounted_price(self):
        if self.discount:
            return round(float(self.price) * float(100 - self.discount) / 100, 2)
        else:
            return self.price

    def get_absolute_url(self):
        return reverse("orders:detail", kwargs={"pk": self.pk})

templates/back_to_top.html
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

templates/base.html
{% load static %}

<html lang="en">

<head>
    {% include 'head.html' %}
</head>

<body>
    {% include 'topbar.html' %}
    {% include 'navbar.html' %}

    {% block content %}{% endblock content %}

    {% include 'footer.html' %}
    {% include 'back_to_top.html' %}

    {% block scripts %}{% endblock scripts %}
</body>

</html>

templates/carousel.html
{% load static %}

<div class="container-fluid mb-5">

    <div class="row border-top px-xl-5">

        <div class="col-lg-12">
            <div id="header-carousel" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner">

                    {% for product in discounted_products %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" style="height: 410px;">
                        <img class="img-fluid" src="{{ product.image.url }}" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">{{ product.discount|stringformat:'d' }}% OFF</h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">{{ product.name }}</h3>
                                <a href="{{ product.get_absolute_url }}" class="btn btn-light py-2 px-3">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

<!--                    <div class="carousel-item active" style="height: 410px;">-->
<!--                        <img class="img-fluid" src="{% static 'img/carousel-1.jpg' %}" alt="Image">-->
<!--                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">-->
<!--                            <div class="p-3" style="max-width: 700px;">-->
<!--                                <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>-->
<!--                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashionable Dress</h3>-->
<!--                                <a href="{{ product_list }}" class="btn btn-light py-2 px-3">Shop Now</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

<!--                    <div class="carousel-item" style="height: 410px;">-->
<!--                        <img class="img-fluid" src="{% static 'img/carousel-2.jpg' %}" alt="Image">-->
<!--                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">-->
<!--                            <div class="p-3" style="max-width: 700px;">-->
<!--                                <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>-->
<!--                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>-->
<!--                                <a href="{{ product_list }}" class="btn btn-light py-2 px-3">Shop Now</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

                </div>

                <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-prev-icon mb-n2"></span>
                    </div>
                </a>

                <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-next-icon mb-n2"></span>
                    </div>
                </a>

            </div>
        </div>
    </div>
</div>

templates/featured.html
{% load static %}

<div class="container-fluid pt-5">

    <div class="row px-xl-5 pb-3">

        <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>

    </div>

</div>

templates/footer.html
{% load static %}

{% url 'index' as index %}
{% url 'products:list' as product_list %}
{% url 'products:cart' as cart %}
{% url 'products:checkout' as checkout %}

<div class="container-fluid bg-secondary text-dark mt-5 pt-5">

    <div class="row px-xl-5">
        <a href="" class="text-decoration-none">
            <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Commerce</h1>
        </a>
    </div>

    <div class="row px-xl-5">

        <div class="col-md-6 mb-5">
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
        </div>

        <div class="col-md-3 mb-5">
        </div>

        <div class="col-md-3 mb-5">
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>

    </div>

</div>

<div class="row border-top border-light mx-xl-5 py-4">
    <div class="col-md-6 px-xl-0">
        <p class="mb-md-0 text-center text-md-left text-dark">
            &copy; <a class="text-dark font-weight-semi-bold" href="#">E-commerce</a>. All Rights Reserved. Designed
            by
            <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
        </p>
    </div>
    <div class="col-md-6 px-xl-0 text-center text-md-right">
        <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
    </div>
</div>

templates/head.html
{% load static %}

<meta charset="utf-8">
<title>Ecommerce Website</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<!-- Favicon -->
<link href="img/favicon.ico" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<script type="text/javascript">
    var user = '{{ request.user }}'

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

</script>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'carousel.html' %}
{% include 'featured.html' %}
{% include 'products_sale.html' %}
{% include 'products_new_arrival.html' %}
{% endblock content %}

{% block scripts %}
{% include 'scripts.html' %}
{% endblock scripts %}

templates/navbar.html
{% load static %}

{% url 'index' as index %}
{% url 'orders:list' as product_list %}
{% url 'orders:cart' as cart %}
{% url 'orders:checkout' as checkout %}

<div class="container-fluid mb-5">

    <div class="row border-top px-xl-5">

        <div class="col-lg-12">

            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{{ index }}" class="nav-item nav-link {% if request.path == index %}active{% endif %}">Home</a>
                        <a href="{{ product_list }}" class="nav-item nav-link {% if request.path == product_list %}active{% endif %}">Shop</a>
                        {% if user.is_authenticated %}
                        <a href="{{ cart }}" class="nav-item nav-link {% if request.path == cart %}active{% endif %}">Cart</a>
                        <a href="{{ checkout }}" class="nav-item nav-link {% if request.path == checkout %}active{% endif %}">Checkout</a>
                        {% endif %}
                    </div>
                    <div class="navbar-nav ml-auto py-0">
                        {% if user.is_authenticated %}
                        <a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Logout</a>
                        {% else %}
                        <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Login</a>
                        <a href="{% url 'accounts:register' %}" class="nav-item nav-link">Register</a>
                        {% endif %}
                    </div>
                </div>
            </nav>

        </div>
    </div>
</div>

templates/products_new_arrival.html
{% load static %}

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Just Arrived</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">

        {% for product in new_arrival_products %}
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            {% include 'product_box.html' %}
        </div>
        {% endfor %}
    </div>
</div>

templates/products_sale.html
{% load static %}

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">On Sale</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">

        {% for product in discounted_products %}
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            {% include 'product_box.html' %}
        </div>
        {% endfor %}
    </div>
</div>

templates/products_suggested.html
{% load static %}

<div class="container-fluid py-5">

    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">You May Also Like</span></h2>
    </div>

    <div class="row px-xl-5">
        <div class="col">
            <div class="owl-carousel related-carousel">

                <div class="card product-item border-0">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="{% static 'img/product-1.jpg' %}" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>

                <div class="card product-item border-0">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="{% static 'img/product-2.jpg' %}" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>

                <div class="card product-item border-0">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="{% static 'img/product-3.jpg' %}" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>

                <div class="card product-item border-0">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="{% static 'img/product-4.jpg' %}" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>

                <div class="card product-item border-0">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="{% static 'img/product-5.jpg' %}" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                        <div class="d-flex justify-content-center">
                            <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

templates/products_trending.html
{% load static %}

<div class="container-fluid pt-5">

    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Trending Products</span></h2>
    </div>

    <div class="row px-xl-5 pb-3">

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-1.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-2.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-3.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-4.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-5.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-6.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-7.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="card product-item border-0 mb-4">
                <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                    <img class="img-fluid w-100" src="{% static 'img/product-8.jpg' %}" alt="">
                </div>
                <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                    <h6 class="text-truncate mb-3">Colorful Stylish Shirt</h6>
                    <div class="d-flex justify-content-center">
                        <h6>$123.00</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between bg-light border">
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                    <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                </div>
            </div>
        </div>

    </div>

</div>

templates/scripts.html
{% load static %}

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

templates/subscribe.html
{% load static %}

<div class="container-fluid bg-secondary my-5">

    <div class="row justify-content-md-center py-5 px-xl-5">

        <div class="col-md-6 col-12 py-5">

            <div class="text-center mb-2 pb-2">
                <h2 class="section-title px-5 mb-3"><span class="bg-secondary px-2">Stay Updated</span></h2>
                <p>Amet lorem at rebum amet dolores. Elitr lorem dolor sed amet diam labore at justo ipsum eirmod duo labore labore.</p>
            </div>

            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control border-white p-4" placeholder="Email Goes Here">
                    <div class="input-group-append">
                        <button class="btn btn-primary px-4">Subscribe</button>
                    </div>
                </div>
            </form>

        </div>

    </div>

</div>